# Generated by Django 4.1.5 on 2023-01-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gin',
            fields=[
                ('gin_id', models.AutoField(primary_key=True, serialize=False)),
                ('gin_description', models.CharField(max_length=200)),
                ('gin_created_at', models.DateField(default=datetime.timezone)),
            ],
            options={
                'verbose_name': 'Джины',
                'verbose_name_plural': 'Джины',
            },
        ),
    ]
