# Generated by Django 4.1.5 on 2023-01-17 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gin',
            name='gin_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gin',
            name='gin_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gin',
            name='gin_description',
            field=models.TextField(),
        ),
    ]
