# Generated by Django 4.1.5 on 2023-01-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gin', '0002_gin_gin_image_alter_gin_gin_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gin',
            name='gin_image',
        ),
    ]
