# Generated by Django 4.1.5 on 2023-03-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gin', '0004_remove_ginsave_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ginsave',
            old_name='post',
            new_name='gin',
        ),
    ]
